
server:
  port: 9117

#database setting
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/sideproject202512
    username: root
    password: mariadb1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    # DBMS dialect setting
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
    #ddl
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true #SQL log
      database: mysql


  # log level setting
logging:
  level:
    root: info
    app.backend: debug
    org.hibernate.SQL : debug
